server:
  port: 8090
spring:
  profiles:
    include:
#      - h2
      - external
      - resilience
      - mysql
      - redis
      - kafka
management:
  endpoints:
    web:
      exposure:
        include: prometheus