external:
  api:
    kakao:
      restKey: 1121988c4a69af314c6fd21552319998
      url: https://dapi.kakao.com/v2/search/blog?
    naver:
      clientId: zFmQ23bty3JJTCniEFts
      clientSecret: 2KJlScoaDX
      url: https://openapi.naver.com/v1/search/blog.json?
